## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df.drop(columns=['EIN','NAME'], inplace=True)
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [4]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [10]:
# Look at APPLICATION_TYPE value counts for binning
application_df['APPLICATION_TYPE'].value_counts()

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [11]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = ['T9', 'T13', 'T12', 'T2', 'T25', 'T14', 'T29', 'T15', 'T17']

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [12]:
# Look at CLASSIFICATION value counts for binning
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [19]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_counts = application_df['CLASSIFICATION'].value_counts()
classification_counts[classification_counts>1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [25]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = classification_counts[classification_counts<1000].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [33]:
# Convert categorical data to numeric with `pd.get_dummies`
dummies_df = pd.get_dummies(application_df[['APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION', 'USE_CASE', 'ORGANIZATION', 'INCOME_AMT', 'SPECIAL_CONSIDERATIONS']])
dummies_df

,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,APPLICATION_TYPE_T8,AFFILIATION_CompanySponsored,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,0,0,0,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,0,0,0,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
3,0,0,0,1,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,1,0
4,0,0,0,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,0,0,0,0,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
34296,0,0,0,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
34297,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34298,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [35]:
# Identify data that is already in numeric form
application_numeric_df = application_df[['STATUS', 'ASK_AMT', 'IS_SUCCESSFUL']]
application_numeric_df

       STATUS   ASK_AMT  IS_SUCCESSFUL
0           1      5000              1
1           1    108590              1
2           1      5000              0
3           1      6692              1
4           1    142590              1
...       ...       ...            ...
34294       1      5000              0
34295       1      5000              0
34296       1      5000              0
34297       1      5000              1
34298       1  36500179              0

[34299 rows x 3 columns]

In [37]:
# Concatenate data into final preprocessed dataframe
application_df_encoded = pd.concat([application_numeric_df, dummies_df], axis=1)
application_df_encoded

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [38]:
# Split our preprocessed data into our features and target arrays
features = application_df_encoded.drop("IS_SUCCESSFUL", axis=1)
target = application_df_encoded["IS_SUCCESSFUL"]
target_names = ["NOT SUCCESSFUL", "SUCCESSFUL"]

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(features, target, random_state=42)

In [39]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [87]:
tf.keras.backend.clear_session()

In [88]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=10, activation="relu", input_dim=43))

# Second hidden layer
# nn.add(tf.keras.layers.Dense(units=2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 10)                440

 dense_1 (Dense)             (None, 1)                 11

=================================================================
Total params: 451 (1.76 KB)
Trainable params: 451 (1.76 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [89]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [90]:
# Train the model
fit_model = nn.fit(X_train, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 3s 3ms/step - loss: 19863.5078 - accuracy: 0.4939
Epoch 2/100
804/804 [==============================] - 2s 3ms/step - loss: 10696.3574 - accuracy: 0.5044
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 12220.8232 - accuracy: 0.4981
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 11500.4561 - accuracy: 0.5197
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 11731.5205 - accuracy: 0.5349
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 18336.6484 - accuracy: 0.5158
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 12085.2295 - accuracy: 0.5031
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 16861.6230 - accuracy: 0.4982
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 5491.8755 - accuracy: 0.5227
Epoch 10/100
804/804 [==============================] - 2s 3ms/step - loss: 7205.5781 - accuracy: 0.5168
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 12518.4434 - accuracy: 0.5122
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 11073.3770 - accuracy: 0.5430
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 17014.7598 - accuracy: 0.4998
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 15942.4707 - accuracy: 0.5580
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 15842.6494 - accuracy: 0.5185
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 9204.1709 - accuracy: 0.5578
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 9738.2061 - accuracy: 0.5686
Epoch 18/100
804/804 [==============================] - 3s 3ms/step - loss: 4521.6216 - accuracy: 0.5351
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 11821.1191 - accuracy: 0.5842
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 17499.1289 - accuracy: 0.5621
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 9179.5820 - accuracy: 0.5592
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 9407.6543 - accuracy: 0.5629
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 1528.7452 - accuracy: 0.6177
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 10881.9932 - accuracy: 0.5630
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 3549.4016 - accuracy: 0.5639
Epoch 26/100
804/804 [==============================] - 2s 3ms/step - loss: 14937.1533 - accuracy: 0.5371
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 12524.9932 - accuracy: 0.5572
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 9883.6426 - accuracy: 0.5552
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 5459.6631 - accuracy: 0.5770
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 10395.0518 - accuracy: 0.5422
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 2741.7588 - accuracy: 0.5753
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 2514.0063 - accuracy: 0.5760
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 13350.8047 - accuracy: 0.5729
Epoch 34/100
804/804 [==============================] - 2s 3ms/step - loss: 2346.6821 - accuracy: 0.5623
Epoch 35/100
804/804 [==============================] - 2s 3ms/step - loss: 16459.8848 - accuracy: 0.6042
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 11523.4258 - accuracy: 0.5764
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 8998.7920 - accuracy: 0.5992
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 9335.2695 - accuracy: 0.5269
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 9994.2686 - accuracy: 0.5627
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 7645.1704 - accuracy: 0.5898
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 4039.5437 - accuracy: 0.5961
Epoch 42/100
804/804 [==============================] - 2s 3ms/step - loss: 6779.7549 - accuracy: 0.6314
Epoch 43/100
804/804 [==============================] - 2s 3ms/step - loss: 13552.0625 - accuracy: 0.5877
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 10632.6133 - accuracy: 0.5795
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 958.4010 - accuracy: 0.6162
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 5807.2256 - accuracy: 0.5811
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 13746.9287 - accuracy: 0.5765
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 7514.0776 - accuracy: 0.5871
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 15026.0938 - accuracy: 0.5964
Epoch 50/100
804/804 [==============================] - 2s 3ms/step - loss: 11547.1182 - accuracy: 0.6109
Epoch 51/100
804/804 [==============================] - 2s 3ms/step - loss: 8211.0488 - accuracy: 0.5676
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 13271.3672 - accuracy: 0.5907
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 7746.1162 - accuracy: 0.6090
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 8954.7021 - accuracy: 0.6078
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 2559.5750 - accuracy: 0.5836
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 10710.2461 - accuracy: 0.6030
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 12720.3936 - accuracy: 0.6003
Epoch 58/100
804/804 [==============================] - 2s 3ms/step - loss: 10052.0693 - accuracy: 0.5811
Epoch 59/100
804/804 [==============================] - 2s 3ms/step - loss: 7687.0073 - accuracy: 0.5816
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 4862.6685 - accuracy: 0.6252
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 1676.1827 - accuracy: 0.6164
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 15671.0732 - accuracy: 0.5209
Epoch 63/100
804/804 [==============================] - 1s 2ms/step - loss: 3294.9290 - accuracy: 0.5515
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 11063.0430 - accuracy: 0.5752
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 5761.6577 - accuracy: 0.6001
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 12105.1328 - accuracy: 0.5773
Epoch 67/100
804/804 [==============================] - 2s 3ms/step - loss: 7669.1523 - accuracy: 0.5930
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 6283.3179 - accuracy: 0.6179
Epoch 69/100
804/804 [==============================] - 2s 2ms/step - loss: 8730.1914 - accuracy: 0.5389
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 8136.6670 - accuracy: 0.5966
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 3342.7046 - accuracy: 0.6279
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 8886.9336 - accuracy: 0.6020
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 8204.0752 - accuracy: 0.5473
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 6201.5610 - accuracy: 0.6109
Epoch 75/100
804/804 [==============================] - 2s 3ms/step - loss: 8017.8032 - accuracy: 0.6216
Epoch 76/100
804/804 [==============================] - 2s 3ms/step - loss: 1588.3538 - accuracy: 0.6224
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 10540.3008 - accuracy: 0.6032
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 7530.3198 - accuracy: 0.5930
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 5072.5981 - accuracy: 0.6279
Epoch 80/100
804/804 [==============================] - 1s 2ms/step - loss: 1516.6469 - accuracy: 0.6174
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 2679.8159 - accuracy: 0.5980
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 11166.3740 - accuracy: 0.5184
Epoch 83/100
804/804 [==============================] - 2s 3ms/step - loss: 7727.1353 - accuracy: 0.6114
Epoch 84/100
804/804 [==============================] - 2s 3ms/step - loss: 8363.3447 - accuracy: 0.5566
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 4991.4873 - accuracy: 0.5926
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 6318.8105 - accuracy: 0.6077
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 3987.9634 - accuracy: 0.6339
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 5124.3130 - accuracy: 0.6093
Epoch 89/100
804/804 [==============================] - 1s 2ms/step - loss: 9266.4639 - accuracy: 0.5645
Epoch 90/100
804/804 [==============================] - 1s 2ms/step - loss: 7219.7827 - accuracy: 0.6051
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 2126.5540 - accuracy: 0.5959
Epoch 92/100
804/804 [==============================] - 2s 3ms/step - loss: 1447.0997 - accuracy: 0.6366
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 6296.7544 - accuracy: 0.5950
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 3983.7361 - accuracy: 0.5994
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 7301.2285 - accuracy: 0.5730
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 1207.8265 - accuracy: 0.6274
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 7665.4219 - accuracy: 0.5316
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 4388.1958 - accuracy: 0.6433
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 7614.8418 - accuracy: 0.5784
Epoch 100/100
804/804 [==============================] - 2s 3ms/step - loss: 6598.3301 - accuracy: 0.6010

In [91]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 4.4955 - accuracy: 0.6899 - 741ms/epoch - 3ms/step
Loss: 4.49553918838501, Accuracy: 0.6899125576019287

In [94]:
# Export our model to HDF5 file
nn.save('AlphabetSoupCharity.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3079: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(