## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df.drop(columns=['EIN','NAME'], inplace=True)
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
application_df['APPLICATION_TYPE'].value_counts()

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = ['T9', 'T13', 'T12', 'T2', 'T25', 'T14', 'T29', 'T15', 'T17']

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_counts = application_df['CLASSIFICATION'].value_counts()
classification_counts[classification_counts>1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = classification_counts[classification_counts<1000].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`, excluding SPECIAL_CONSIDERATIONS, INCOME_AMT and APPLICATION_TYPE to optimize
dummies_df = pd.get_dummies(application_df[['AFFILIATION', 'CLASSIFICATION', 'USE_CASE', 'ORGANIZATION']])
dummies_df

,AFFILIATION_CompanySponsored,AFFILIATION_Family/Parent,AFFILIATION_Independent,AFFILIATION_National,AFFILIATION_Other,AFFILIATION_Regional,CLASSIFICATION_C1000,CLASSIFICATION_C1200,CLASSIFICATION_C2000,CLASSIFICATION_C2100,...,CLASSIFICATION_Other,USE_CASE_CommunityServ,USE_CASE_Heathcare,USE_CASE_Other,USE_CASE_Preservation,USE_CASE_ProductDev,ORGANIZATION_Association,ORGANIZATION_Co-operative,ORGANIZATION_Corporation,ORGANIZATION_Trust
0,0,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,1,1,0,0,0
1,0,0,1,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,1,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
3,1,0,0,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,1
4,0,0,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,0,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,1,1,0,0,0
34295,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
34296,1,0,0,0,0,0,0,0,1,0,...,0,0,0,0,1,0,1,0,0,0
34297,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
34298,0,0,1,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,1,0,0

In [10]:
# Identify data that is already in numeric form, excluding STATUS and ASK_AMT to optimize
application_numeric_df = application_df['IS_SUCCESSFUL']
application_numeric_df

0        1
1        1
2        0
3        1
4        1
        ..
34294    0
34295    0
34296    0
34297    1
34298    0
Name: IS_SUCCESSFUL, Length: 34299, dtype: int64

In [11]:
# Concatenate data into final preprocessed dataframe
application_df_encoded = pd.concat([application_numeric_df, dummies_df], axis=1)
application_df_encoded

,IS_SUCCESSFUL,AFFILIATION_CompanySponsored,AFFILIATION_Family/Parent,AFFILIATION_Independent,AFFILIATION_National,AFFILIATION_Other,AFFILIATION_Regional,CLASSIFICATION_C1000,CLASSIFICATION_C1200,CLASSIFICATION_C2000,...,CLASSIFICATION_Other,USE_CASE_CommunityServ,USE_CASE_Heathcare,USE_CASE_Other,USE_CASE_Preservation,USE_CASE_ProductDev,ORGANIZATION_Association,ORGANIZATION_Co-operative,ORGANIZATION_Corporation,ORGANIZATION_Trust
0,1,0,0,1,0,0,0,1,0,0,...,0,0,0,0,0,1,1,0,0,0
1,1,0,0,1,0,0,0,0,0,1,...,0,0,0,0,1,0,0,1,0,0
2,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
3,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,0,1
4,1,0,0,1,0,0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,0,0,0,1,0,0,0,1,0,0,...,0,0,0,0,0,1,1,0,0,0
34295,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
34296,0,1,0,0,0,0,0,0,0,1,...,0,0,0,0,1,0,1,0,0,0
34297,1,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
34298,0,0,0,1,0,0,0,1,0,0,...,0,0,0,0,1,0,0,1,0,0

In [12]:
# Split our preprocessed data into our features and target arrays
features = application_df_encoded.drop("IS_SUCCESSFUL", axis=1)
target = application_df_encoded["IS_SUCCESSFUL"]
target_names = ["NOT SUCCESSFUL", "SUCCESSFUL"]

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(features, target, random_state=42)

In [13]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [22]:
tf.keras.backend.clear_session()

In [23]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
nn = tf.keras.models.Sequential()

# First hidden layer, reduce nodes to optimize
nn.add(tf.keras.layers.Dense(units=5, activation="relu", input_dim=21))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 5)                 110

 dense_1 (Dense)             (None, 1)                 6

=================================================================
Total params: 116 (464.00 Byte)
Trainable params: 116 (464.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [24]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [25]:
# Train the model, reduce epochs to optimize
fit_model = nn.fit(X_train, y_train, epochs=25)

Epoch 1/25
804/804 [==============================] - 2s 2ms/step - loss: 0.6428 - accuracy: 0.6599
Epoch 2/25
804/804 [==============================] - 2s 2ms/step - loss: 0.6062 - accuracy: 0.6869
Epoch 3/25
804/804 [==============================] - 2s 2ms/step - loss: 0.6012 - accuracy: 0.6879
Epoch 4/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5979 - accuracy: 0.6927
Epoch 5/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5955 - accuracy: 0.6968
Epoch 6/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5937 - accuracy: 0.6968
Epoch 7/25
804/804 [==============================] - 2s 3ms/step - loss: 0.5923 - accuracy: 0.6987
Epoch 8/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5914 - accuracy: 0.6990
Epoch 9/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5907 - accuracy: 0.6987
Epoch 10/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5901 - accuracy: 0.6990
Epoch 11/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5897 - accuracy: 0.6979
Epoch 12/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5893 - accuracy: 0.6985
Epoch 13/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5889 - accuracy: 0.6986
Epoch 14/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5886 - accuracy: 0.6990
Epoch 15/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5884 - accuracy: 0.6989
Epoch 16/25
804/804 [==============================] - 2s 3ms/step - loss: 0.5882 - accuracy: 0.6997
Epoch 17/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5882 - accuracy: 0.6992
Epoch 18/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5880 - accuracy: 0.6996
Epoch 19/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5880 - accuracy: 0.6989
Epoch 20/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5876 - accuracy: 0.6999
Epoch 21/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5876 - accuracy: 0.6994
Epoch 22/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5876 - accuracy: 0.6995
Epoch 23/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5877 - accuracy: 0.6992
Epoch 24/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5874 - accuracy: 0.6998
Epoch 25/25
804/804 [==============================] - 2s 3ms/step - loss: 0.5875 - accuracy: 0.6992

In [26]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.8463 - accuracy: 0.6886 - 459ms/epoch - 2ms/step
Loss: 0.8463323712348938, Accuracy: 0.6886297464370728

In [27]:
# Export our model to HDF5 file
nn.save('AlphabetSoupCharity_Optimized.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3079: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(